version: '3'

services:
  #-------------------------------
  backend1:
    build:
      context: ./
    environment:
      - NUMBER=1
    container_name: 'backend1'
    networks:
      - docker_network
  #--------------------------------
  backend2:
    build:
      context: ./
    environment:
      - NUMBER=2
    container_name: 'backend2'
    networks:
      - docker_network
  #--------------------------------
  haproxy:
    depends_on:
      - backend1
      - backend2
    image: haproxy:latest
    container_name: haproxy
    volumes:
      - "./haproxy:/usr/local/etc/haproxy"
    ports:
      - "9090:80"
    networks:
      - docker_network
    

networks:
  docker_network:
    driver: bridge
